### ISSUE TITLE
Combine forces at ember-flatpickr

### ISSUE THREAD

**Issue by RobbieTheWagner** [jakkor/ember-cli-flatpickr#4]
Would you like to work together on https://github.com/shipshapecode/ember-flatpickr rather than doing things separately? I'd be glad to make you a collaborator on the repo.

**Comment by jakkor** [comment]
The problem that I had with that is that the project that use flatpickr is on hold, so I wasn't able to test my work in production environment. But I will try to use yours now. Is there anything that you want to add there or by working together you mean to correct issues if people will have some ?
Maybe we should talk on slack or something like that ?
